# -*- coding: utf-8 -*-
{
    'name': "partner",
    'summary': """
         宝舜基础档案""",
    'description': """
   Customer, company information...
    """,
    'author': "Duyafei",
    'website': "http://www.yourcompany.com",
    'category': 'Partner',
    'version': '0.1',
    'depends': ['base', 'mail'],
    'data': [
        'views/material_codes.xml',
        'views/res_users.xml',
        'views/account_partner.xml',
        'views/account_users.xml',
        'views/account_company.xml',
        'views/partner_company.xml',
        'views/partner_partner.xml',
        'views/partner_users.xml',
        'views/contact.xml',
        'views/bank_table.xml',
        'views/department.xml',
        'views/department_category.xml',
        'views/post.xml',
        'views/base.xml',
        'views/cron.xml',
        'views/quality_requirements.xml',
        'views/production_system.xml',
        'views/area.xml',
        'views/bank.xml',
        # 'mes/process.xml',
        'views/project.xml',
        'views/cash_flow.xml',
        'views/financial_assets.xml',
        'views/settlement_style.xml',
        'views/is_no.xml',
        'views/budget_items.xml',
        'views/budget_device.xml',
        'views/expenses_type.xml',
        'views/budget_department.xml',
        'views/expenditure_business.xml',
        'views/expend_items.xml',
        'views/expend_detail.xml',
        'views/management_caliber.xml',
        'views/contract_category.xml',
        'views/bill_type.xml',
        'views/document.xml',
        'views/bank_type.xml',
        'views/other_name.xml',
        'views/change_partner.xml',
        'views/account_state.xml',
        'views/material_classification.xml',
        'views/time_dimension.xml',
        'crm/fee_type.xml',
        'crm/way_to.xml',
        'crm/transport_mode.xml',
        'crm/payment_method.xml',
        'crm/contract_implement.xml',
        'ding_views/ding_department.xml',
        'ding_views/ding_message.xml',
        'ding_views/ding_person.xml',
        'ding_views/ding_setting.xml',
        'financial_needs_views/currency_type.xml',
        'financial_needs_views/currency.xml',
        'financial_needs_views/account_type.xml',
        'financial_needs_views/account_type_detail.xml',
        'financial_needs_views/contract_mode.xml',
        'financial_needs_views/advance_type.xml',
        'financial_needs_views/allowance_account.xml',
        'financial_needs_views/allowance_account_detail.xml',
        'financial_needs_views/receive_type.xml',
        'financial_needs_views/receive_type_detail.xml',
        'financial_needs_views/asset_type.xml',
        'financial_needs_views/intangible_assets.xml',
        'financial_needs_views/long_spending.xml',
        'financial_needs_views/deferred_tax_assets.xml',
        'financial_needs_views/financial_cost.xml',
        'financial_needs_views/nonoperating_re.xml',
        'em/class_group.xml',
        'em/equipment_state.xml',
        'em/fault.xml',
        'em/inventory_organization.xml',
        'em/position.xml',
        'em/standard.xml',
        'em/warehouse_base.xml',
        'em/settlement_type.xml',
        'fm/account.xml',
        'fm/account_type.xml',
        'fm/account_tag.xml',
        'fm/account_journal.xml',
        'fm/account_bill_type.xml',
        'fm/account_depreciation.xml',
        'fm/account_asset_type.xml',
        'fm/accounting_interval.xml',
        'fm/nc_type.xml',
        'fm/account_tax.xml',
        'fm/cash_flow_items.xml',
        'mes/mes_area.xml',
        'mes/mes_class_time.xml',
        'mes/mes_block.xml',
        'security/partner_security.xml',
        'security/ir.model.access.csv',
        'views/views.xml',
    ],
    'sequence': 30,
    'installable': True,
    'application': True,
    'auto_install': False,
}

